# Generated by Django 4.1.2 on 2022-10-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_make_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('type', models.CharField(max_length=30)),
            ],
        ),
    ]
