# Generated by Django 4.1.2 on 2022-10-22 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_game_max_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_img',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='max_level',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Max level cannot be below 1.')]),
        ),
    ]
