# Generated by Django 4.1.2 on 2022-10-26 06:39

import django.core.validators
from django.db import migrations, models
import my_musicapp.web.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

    ]
