# Generated by Django 4.1.2 on 2022-10-26 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_album_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['pk']},
        ),
    ]
