# Generated by Django 4.1.2 on 2022-10-30 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinValueValidator(2, message='The username must be a minimum of 2 chars')]),
        ),
    ]
