# Generated by Django 4.1.2 on 2022-10-30 10:18

from django.db import migrations, models
import examtask.web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=10, validators=[examtask.web.models.min_name_validator]),
        ),
    ]
